export const SCENE_LOGIN = 'LOGIN'
export const SCENE_SPLASH_SCREEN = 'SPLASH_SCREEN'
export const SCENE_INDEX = 'INDEX'
export const SCENE_REGISTER = 'REGISTER'
export const SCENE_NOTEEDITOR = 'NOTEEDITOR'
export const SCENE_HOME = 'HOME'
export const SCENE_FEEDBACK = 'FEEDBACK'
export const SCENE_ABOUT_US = 'SCENE_ABOUT_US'
export const SCENE_ABOUT_US_WEB = 'SCENE_ABOUT_US_WEB'
export const SCENE_SETTING = 'SCENE_SETTING'
export const SCENE_CONNECTION = 'SCENE_CONNECTION'

// 2.0
export const SCENE_LOGIN_OPTIONS = 'SCENE_LOGIN_OPTIONS'
export const SCENE_LOGIN_SIGNIN = 'SCENE_LOGIN_SIGNIN'
export const SCENE_LOGIN_SIGNUP = 'SCENE_LOGIN_SIGNUP'
export const SCENE_LOGIN_NICKNAME = 'SCENE_LOGIN_NICKNAME'
export const SCENE_LOGIN_GENDER = 'SCENE_LOGIN_GENDER'

