export const SCENE_LOGIN = 'LOGIN'
export const SCENE_SPLASH_SCREEN = 'SPLASH_SCREEN'
export const SCENE_INDEX = 'INDEX'
export const SCENE_HOME = 'HOME'

// 2.0
export const SCENE_LOGIN_OPTIONS = 'LOGIN_OPTIONS'
export const SCENE_LOGIN_SIGNIN = 'LOGIN_SIGNIN'
export const SCENE_LOGIN_SIGNUP = 'LOGIN_SIGNUP'
export const SCENE_LOGIN_NICKNAME = 'LOGIN_NICKNAME'
export const SCENE_LOGIN_GENDER = 'LOGIN_GENDER'

export const SCENE_NEW_DIARY = 'NEW_DIARY'
export const SCENE_DIARY_DETAIL = 'DIARY_DETAIL'

export const SCENE_PROFILE_BADGE = 'PROFILE_BADGE'
export const SCENE_PROFILE_EDIT = 'PROFILE_EDIT'
export const SCENE_PROFILE_MATCH = 'PROFILE_MATCH'
export const SCENE_PROFILE_MODE = 'PROFILE_MODE'
export const SCENE_PROFILE_SYNC = 'PROFILE_SYNC'
